{{- if or .Values.startupConfig .Values.targetManagerConfig }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sparrow.fullname" . }}
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
data:
  {{- if .Values.startupConfig}}
  .sparrow.yaml: {{ toYaml .Values.startupConfig | b64enc }}
  {{- end }}
  {{- if .Values.targetManagerConfig}}
  tmconfig.yaml: {{ toYaml .Values.targetManagerConfig | b64enc }}
  {{- end }}
{{- end }}
