name: Test - SAST

on:
  push:
  schedule:
    # Schedule the workflow to run at 00:00 on Sunday UTC time.
    - cron: "0 0 * * 0"

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
