name: test

on:
  pull_request:
    branches:
      - main

env:
  PRIVATE_GO_SERVER: ${{ secrets.PRIVATE_GO_SERVER }}
  GOPRIVATE: ${{ secrets.PRIVATE_GO_SERVER }}
  PRIVATE_SERVER_TOKEN: ${{ secrets.PRIVATE_SERVER_TOKEN }}

jobs:
  test_go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Test
        run: |
          echo "machine $PRIVATE_GO_SERVER" >> ~/.netrc &&\
          echo "    login __token__" >> ~/.netrc &&\
          echo "    password $PRIVATE_SERVER_TOKEN" >> ~/.netrc
          go mod download
          go test --race --coverprofile cover.out -v ./...
